version: '2.7'

services:
  backend:
    build: .
    container_name: backend
    ports:
      - 8085:8081
    depends_on:
      - postgres
    environment:
      - POSTGRES_URL=postgres

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - 8086:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
